---
- name: Docker Login
  ansible.builtin.command:
    cmd: echo {{ dockerhub_password }} | docker login -u {{ dockerhub_username }} --password-stdin

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Start Docker and enable at boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Pull Jenkins Docker image
  community.docker.docker_image:
    name: jenkins/jenkins
    tag: lts-jdk11
    source: pull

- name: Create Jenkins data directory
  ansible.builtin.file:
    path: ~/jenkins_data
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Run Jenkins container
  community.docker.docker_container:
    name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/jenkins_data:/var/jenkins_home
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"

# - name: Create directories in Jenkins container
#   ansible.builtin.command:
#     cmd: docker exec jenkins mkdir -p /var/jenkins_home/{{ item }}
#   loop:
#     - casc_configs
#     - job-dsl

# - name: Copy files to Jenkins server
#   ansible.builtin.copy:
#     src: "files/{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: '0644'
#   become: true
#   with_items:
#     - { src: 'jenkins-casc.yml', dest: '/tmp/jenkins-casc.yml' }
#     - { src: 'django-build-job.groovy', dest: '/tmp/django-build-job.groovy' }

# - name: Copy configuration file to Jenkins Container
#   block:
#     - name: Copy jenkins-casc from remote host to Jenkins Conatiner
#       ansible.builtin.command: docker cp /tmp/jenkins-casc.yml jenkins:/var/jenkins_home/casc_configs/jenkins.yml
#       become: true
    
#     - name: Copy django-build-job from remote host to Jenkins Container
#       ansible.builtin.command: docker cp /tmp/django-build-job.groovy jenkins:/var/jenkins_home/job-dsl/djangoAppBuildJob.groovy
#       become: true

- name: Create casc_configs directory in Jenkins container
  ansible.builtin.command:
    cmd: docker exec jenkins mkdir -p /var/jenkins_home/casc_configs

- name: Copy JCasC configuration file to Jenkins server
  block:
    - name: Copy JCasC configuration file to remote host
      ansible.builtin.copy:
        src: "files/jenkins-casc.yml"
        dest: "/tmp/jenkins-casc.yml"
        mode: '0644'
      become: true

    - name: Copy from remote host to Jenkins server
      ansible.builtin.command: docker cp /tmp/jenkins-casc.yml jenkins:/var/jenkins_home/casc_configs/jenkins.yml
      become: true

- name: Install Jenkins plugins
  vars:
    jenkins_plugins:
      - git
      - credentials
      - job-dsl
      - configuration-as-code
      - github-branch-source
      - github
      - docker-workflow
      - pipeline-github-lib
      - pipeline-stage-view
  ansible.builtin.command: >
    docker exec jenkins bash -c 'jenkins-plugin-cli --plugins {{ jenkins_plugins | join(" ") }}'
  register: result
  changed_when: result.stdout.find('No updates found') == -1
  until: result.rc == 0
  retries: 5
  delay: 60

- name: Restart Jenkins container
  community.docker.docker_container:
    name: jenkins
    state: started
    restart: true
