version: '3.8'

services:
  web:
    build:
      context: ./app/
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./app/.env
    depends_on:
      - db
  
  proxy:
    build:
      context: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - '8080:8080'
    depends_on:
      - web
    
  db:
    image: postgres:14.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env

volumes:
  postgres_data:
  static_volume:
  media_volume:
