apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-chart.fullname" . }}
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "django-chart.fullname" . }}-configmap
            - secretRef:
                name: {{ include "django-chart.fullname" . }}-secret
          volumeMounts:
            - name: staticfiles
              mountPath: /home/app/web/staticfiles
            - name: mediafiles
              mountPath: /home/app/web/mediafiles
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.staticfiles }}
        - name: mediafiles
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.mediafiles }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
