apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-chart.fullname" . }}-secret
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | b64enc | quote }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.superuser.DJANGO_SUPERUSER_USERNAME | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.superuser.DJANGO_SUPERUSER_PASSWORD | b64enc | quote }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.superuser.DJANGO_SUPERUSER_EMAIL | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc | quote }}
