replicaCount: 2

image:
  repository: "h1zardian/cicd-pipeline-image"
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 8000

resources: {}

volumes:
  staticfiles: django-staticfiles-pvc
  mediafiles: django-mediafiles-pvc

nodeSelector: {}

tolerations: []

affinity: {}
