---
- name: Install Buildah
  hosts: buildah
  gather_facts: false
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: true

    - name: Install required packages
      ansible.builtin.package:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'bats', 'btrfs-progs', 'git', 'go-md2man', 'golang', 'libapparmor-dev', 'libglib2.0-dev', 'libgpgme11-dev', 'libseccomp-dev', 'libselinux1-dev', 'make', 'skopeo', 'containernetworking-plugins']
        state: present
      become: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Install Buildah
      ansible.builtin.apt:
        name: buildah
        state: present

    - name: Create .docker directory
      ansible.builtin.file:
        path: /home/ubuntu/.docker
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Add Docker registry login credentials
      ansible.builtin.copy:
        dest: /home/ubuntu/.docker/config.json
        content: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "{{ (lookup('env', 'DOCKER_HUB_USERNAME') + ':' + lookup('env', 'DOCKER_HUB_AUTH')) | b64encode }}"
              }
            }
          }
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      no_log: true
