---
- name: Install Buildah
  hosts: buildah
  gather_facts: false
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: true

    - name: Install Buildah
      ansible.builtin.apt:
        name: buildah
        state: present

    - name: Create .docker directory
      ansible.builtin.file:
        path: /home/ubuntu/.docker
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Add Docker registry login credentials
      ansible.builtin.copy:
        dest: /home/ubuntu/.docker/config.json
        content: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "{{ lookup('env', 'DOCKER_HUB_AUTH') }}"
              }
            }
          }
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      no_log: true
