---
- name: Provision EC2 Instance
  hosts: localhost
  gather_facts: false
  roles:
    - provision-ec2

- name: Install Buildah on EC2 Instance
  hosts: buildah
  gather_facts: false
  become: true
  roles:
    - install-buildah
