---
- name: Ensure namespaces exist
  kubernetes.core.k8s:
    name: "{{ item.namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  with_items: "{{ charts }}"

- name: Install Helm chart for Django and Monitoring
  kubernetes.core.helm:
    chart_ref: "{{ item.chart_path }}"
    release_namespace: "{{ item.namespace }}"
    release_name: "{{ item.release_name }}"
    state: present
    values:
      SQL_HOST: "{{ terraform_output.outputs['db_instance_endpoint']['value'] if item.name == 'django' else omit }}"
    values_files:
      - "{{ item.values_path }}"
  with_items: "{{ charts }}"
