jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
crumbIssuer:
  standard:
    excludeClientIPFromCrumb: false
unclassified:
  githubpluginconfig:
    configs:
      - name: "h1zardian"
        apiUrl: "https://api.github.com"
        credentialsId: "github"
  jobs:
    - script: >
        pipelineJob('DjangoAppBuild') {
          definition {
            cpsScm {
              scm {
                git {
                  remote { url('https://github.com/h1zardian/cicd-pipeline-project.git') }
                  branches('main')
                  extensions {
                    wipeOutWorkspace()
                    cleanAfterCheckout()
                  }
                }
              }
              scriptPath('app/jenkinsfile')
            }
          }
          triggers {
            githubPush()
          }
        }
