name: Build and push Docker images

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: DOCKER_HUB_AUTH,DOCKER_HUB_USERNAME
        script: |
          cd /home/ubuntu/
          if [ -d "/home/ubuntu/cicd-pipeline-project" ]; then
          rm -rf cicd-pipeline-project
          fi
          git clone https://github.com/h1zardian/cicd-pipeline-project.git
          cd /home/ubuntu/cicd-pipeline-project/app
          echo $DOCKER_HUB_AUTH | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          buildah bud -t h1zardian/cicd-pipeline-image:${{ github.sha }} .
          buildah bud -t h1zardian/cicd-pipeline-image:latest .
          buildah push h1zardian/cicd-pipeline-image