name: Build and push Docker images

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        # envs: DOCKER_HUB_AUTH,DOCKER_HUB_USERNAME
        script: |
          cd /home/ubuntu/
          if [ -d "/home/ubuntu/cicd-pipeline-project" ]; then
          rm -rf cicd-pipeline-project
          fi
          git clone https://github.com/h1zardian/cicd-pipeline-project.git
          cd cicd-pipeline-project/app
          COMMIT_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-6)
          buildah build -f Dockerfile -t docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/cicd-pipeline-image:$COMMIT_SHA_SHORT -t docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/cicd-pipeline-image:latest
          buildah push --creds ${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_AUTH }} docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/cicd-pipeline-image:$COMMIT_SHA_SHORT
          buildah push --creds ${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_AUTH }} docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/cicd-pipeline-image:latest
          buildah rmi --all