name: Build and push Docker images

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: DOCKER_HUB_AUTH
        script: |
          cd /path/to/your/repo/cicd-pipeline-project/app
          sudo -u buildah buildah bud -t your_dockerhub_username/your_image_name:${{ github.sha }} .
          sudo -u buildah buildah bud -t your_dockerhub_username/your_image_name:latest .
          sudo -u buildah buildah push your_dockerhub_username/your_image_name:${{ github.sha }}
          sudo -u buildah buildah push your_dockerhub_username/your_image_name:latest
