name: Build and push Docker images

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: DOCKER_HUB_AUTH
        script: |
          cd cicd-pipeline-project/app
          sudo buildah bud -t h1zardian/cicd-pipeline-image:${{ github.sha }} .
          sudo buildah bud -t h1zardian/cicd-pipeline-image:latest .
          sudo buildah push h1zardian/cicd-pipeline-image:${{ github.sha }}
          sudo buildah push h1zardian/cicd-pipeline-image:latest
